"""Built-in compliance calendar rules (the super admin can change them: Admin → GST config → Compliance calendar).

See services/compliance_calendar.py for the rule format. Kept free of imports so the configuration store can use it."""

GST_STATES_22 = "22,23,24,25,26,27,29,30,31,32,33,34,35,36,37"  # QRMP GSTR-3B on the 22nd; other states the 24th

COMPANIES = ["PRIVATE_LIMITED", "PUBLIC_LIMITED", "OPC"]
NON_COMPANY = ["PROPRIETORSHIP", "PARTNERSHIP", "LLP", "HUF", "TRUST_SOCIETY", "OTHER"]

GST_LATE = ("Late fee ₹{late_fee_per_day} per day (₹20 per day for a nil return), up to the maximum fixed for your "
            "turnover; interest at {interest_rate}% a year on tax paid late.")

DEFAULT_RULES: list[dict] = [
    # ------------------------------------------------------------------ GST — regular taxpayers
    dict(code="GSTR1_M", name="GSTR-1 (monthly)", authority="GST", link="gst_returns", frequency="MONTHLY",
         applies={"gst": ["REGULAR"], "gst_filing": "MONTHLY"}, due={"months_after": 1, "day": 11},
         fee_per_day="late_fee_per_day", fee_cap=10000,
         description="Details of sales invoices, credit / debit notes. Your buyers' input tax credit depends on it.",
         penalty="Late fee ₹{late_fee_per_day} per day (₹20 for nil), capped by turnover. Buyers may hold payments "
                 "until your invoices appear in their GSTR-2B."),
    dict(code="GSTR3B_M", name="GSTR-3B (monthly) and GST payment", authority="GST", link="gst_returns",
         frequency="MONTHLY", applies={"gst": ["REGULAR"], "gst_filing": "MONTHLY"}, due={"months_after": 1, "day": 20},
         fee_per_day="late_fee_per_day", fee_cap=10000,
         description="Summary return: tax on sales, input tax credit and net GST paid.",
         penalty=GST_LATE + " Not filing for two or more periods can block e-way bill generation."),
    dict(code="GSTR1_Q", name="GSTR-1 (quarterly, QRMP)", authority="GST", link="gst_returns", frequency="QUARTERLY",
         applies={"gst": ["REGULAR"], "gst_filing": "QUARTERLY"}, due={"months_after": 1, "day": 13},
         fee_per_day="late_fee_per_day", fee_cap=10000,
         description="Quarterly statement of sales. B2B invoices of the first two months may be uploaded in IFF by the 13th.",
         penalty="Late fee ₹{late_fee_per_day} per day (₹20 for nil), capped by turnover."),
    dict(code="PMT06", name="GST payment for the month (PMT-06, QRMP)", authority="GST", link="gst_payment",
         frequency="MONTHLY", months_in_quarter=[1, 2], applies={"gst": ["REGULAR"], "gst_filing": "QUARTERLY"},
         due={"months_after": 1, "day": 25},
         description="Tax for the first and second month of the quarter (fixed-sum or self-assessment method).",
         penalty="Interest at {interest_rate}% a year on tax paid late."),
    dict(code="GSTR3B_Q", name="GSTR-3B (quarterly, QRMP)", authority="GST", link="gst_returns", frequency="QUARTERLY",
         applies={"gst": ["REGULAR"], "gst_filing": "QUARTERLY"},
         due={"months_after": 1, "day": 24, "state_day": {s: 22 for s in GST_STATES_22.split(",")}},
         fee_per_day="late_fee_per_day", fee_cap=10000,
         description="Quarterly summary return. Due on the 22nd or 24th depending on your state.", penalty=GST_LATE),
    dict(code="GSTR9", name="GSTR-9 annual return", authority="GST", link="gst_returns", frequency="YEARLY",
         applies={"gst": ["REGULAR"]}, due={"dates": [{"month": 12, "day": 31}]},
         description="Annual return for the financial year (optional for aggregate turnover up to ₹2 crore — check the current limit).",
         penalty="Late fee per day depending on turnover, with a cap linked to turnover."),
    # ------------------------------------------------------------------ GST — composition
    dict(code="CMP08", name="CMP-08 (composition tax payment)", authority="GST", link="gst_returns",
         frequency="QUARTERLY", applies={"gst": ["COMPOSITION"]}, due={"months_after": 1, "day": 18},
         fee_per_day="late_fee_per_day", fee_cap=10000,
         description="Quarterly statement and payment of composition tax.", penalty=GST_LATE),
    dict(code="GSTR4", name="GSTR-4 annual return (composition)", authority="GST", link="gst_returns",
         frequency="YEARLY", applies={"gst": ["COMPOSITION"]}, due={"dates": [{"month": 4, "day": 30}]},
         fee_per_day="late_fee_per_day", fee_cap=2000,
         description="Annual return of a composition taxpayer.",
         penalty="Late fee ₹{late_fee_per_day} per day (₹20 for nil), capped at ₹2,000."),
    # ------------------------------------------------------------------ TDS
    dict(code="TDS_PAY", name="TDS deposit", authority="TDS", link="income_tax_portal", frequency="MONTHLY",
         applies={"requires": ["tds"]}, due={"months_after": 1, "day": 7},
         month_overrides={"3": {"months_after": 1, "day": 30}},
         description="Tax deducted in the month, paid by challan (March deductions by 30 April).",
         penalty="Interest 1.5% a month from deduction to payment (1% a month if not deducted); expense may be disallowed."),
    dict(code="TDS_RET", name="TDS return (24Q / 26Q)", authority="TDS", link="tds_traces", frequency="QUARTERLY",
         applies={"requires": ["tds"]}, due={"months_after": 1, "day": 31},
         quarter_overrides={"4": {"months_after": 2, "day": 31}},
         description="Quarterly statement of TDS deducted and paid. Issue TDS certificates after filing.",
         penalty="Late fee ₹200 per day (section 234E) up to the TDS amount; penalty may also apply (section 271H)."),
    # ------------------------------------------------------------------ income tax
    dict(code="ADV_TAX", name="Advance tax", authority="INCOME_TAX", link="income_tax_portal", frequency="YEARLY",
         applies={}, due={"within_fy": True, "dates": [
             {"month": 6, "day": 15, "label": "1st instalment (15%)"}, {"month": 9, "day": 15, "label": "2nd instalment (45%)"},
             {"month": 12, "day": 15, "label": "3rd instalment (75%)"}, {"month": 3, "day": 15, "label": "Last instalment (100%)"}]},
         description="Payable when the year's tax is ₹10,000 or more (presumptive-tax businesses pay all by 15 March).",
         penalty="Interest 1% a month on the shortfall (sections 234B / 234C)."),
    dict(code="ITR", name="Income-tax return", authority="INCOME_TAX", link="income_tax_portal", frequency="YEARLY",
         applies={"entities": NON_COMPANY, "excludes": ["tax_audit"]}, due={"dates": [{"month": 7, "day": 31}]},
         description="Return of income for businesses whose accounts are not required to be audited.",
         penalty="Late fee up to ₹5,000 (₹1,000 if income is up to ₹5 lakh), interest under section 234A; some losses "
                 "cannot be carried forward."),
    dict(code="ITR_AUDIT", name="Income-tax return (audit case)", authority="INCOME_TAX", link="income_tax_portal",
         frequency="YEARLY", applies={"entities": NON_COMPANY, "requires": ["tax_audit"]},
         due={"dates": [{"month": 10, "day": 31}]}, description="Return of income where a tax audit applies.",
         penalty="Late fee up to ₹5,000, interest under section 234A; some losses cannot be carried forward."),
    dict(code="ITR_CO", name="Income-tax return (company)", authority="INCOME_TAX", link="income_tax_portal",
         frequency="YEARLY", applies={"entities": COMPANIES}, due={"dates": [{"month": 10, "day": 31}]},
         description="Company income-tax return (ITR-6).",
         penalty="Late fee up to ₹5,000, interest under section 234A; losses cannot be carried forward."),
    dict(code="TAX_AUDIT", name="Tax audit report (Form 3CA/3CB-3CD)", authority="INCOME_TAX", link="income_tax_portal",
         frequency="YEARLY", applies={"requires": ["tax_audit"]}, due={"dates": [{"month": 9, "day": 30}]},
         description="Audit report by a chartered accountant, uploaded before the return.",
         penalty="Penalty 0.5% of turnover, up to ₹1,50,000 (section 271B)."),
    # ------------------------------------------------------------------ companies (MCA)
    dict(code="AGM", name="Annual general meeting", authority="MCA", link="mca_portal", frequency="YEARLY",
         applies={"entities": ["PRIVATE_LIMITED", "PUBLIC_LIMITED"]}, due={"dates": [{"month": 9, "day": 30}]},
         description="Adopt the audited accounts; within six months of the year end.",
         penalty="Penalty on the company and officers in default, with a further amount for each day the default continues."),
    dict(code="ADT1", name="ADT-1 (auditor appointment)", authority="MCA", link="mca_portal", frequency="YEARLY",
         applies={"entities": ["PRIVATE_LIMITED", "PUBLIC_LIMITED"]}, due={"dates": [{"month": 10, "day": 14}]},
         description="Within 15 days of the AGM where the auditor is appointed (usually every 5 years).",
         penalty="Additional fee as per the MCA fee rules for each day of delay."),
    dict(code="AOC4", name="AOC-4 (financial statements)", authority="MCA", link="mca_portal", frequency="YEARLY",
         applies={"entities": ["PRIVATE_LIMITED", "PUBLIC_LIMITED"]}, due={"dates": [{"month": 10, "day": 30}]},
         description="File the audited financial statements within 30 days of the AGM.",
         penalty="Additional fee ₹100 per day of delay; penalties on the company and officers may apply."),
    dict(code="AOC4_OPC", name="AOC-4 (financial statements, OPC)", authority="MCA", link="mca_portal",
         frequency="YEARLY", applies={"entities": ["OPC"]}, due={"dates": [{"month": 9, "day": 27}]},
         description="One Person Company: within 180 days of the year end.",
         penalty="Additional fee ₹100 per day of delay; penalties on the company and officers may apply."),
    dict(code="MGT7", name="MGT-7 / MGT-7A (annual return)", authority="MCA", link="mca_portal", frequency="YEARLY",
         applies={"entities": COMPANIES}, due={"dates": [{"month": 11, "day": 29}]},
         description="Annual return of the company within 60 days of the AGM (MGT-7A for small companies and OPCs).",
         penalty="Additional fee ₹100 per day of delay; penalties on the company and officers may apply."),
    dict(code="DPT3", name="DPT-3 (deposits and loans)", authority="MCA", link="mca_portal", frequency="YEARLY",
         applies={"entities": COMPANIES}, due={"dates": [{"month": 6, "day": 30}]},
         description="Return of deposits / money received that is not a deposit, as on 31 March.",
         penalty="Additional fee as per the MCA fee rules; penalties under the Companies Act may apply."),
    dict(code="DIR3KYC", name="Director / partner KYC (DIR-3 KYC)", authority="MCA", link="mca_portal",
         frequency="YEARLY", applies={"entities": COMPANIES + ["LLP"]}, due={"dates": [{"month": 9, "day": 30}]},
         description="KYC of every director / designated partner holding a DIN — check the current frequency on the MCA portal.",
         penalty="Fee of ₹5,000 for late KYC; the DIN is deactivated until it is done."),
    # ------------------------------------------------------------------ LLP
    dict(code="LLP11", name="LLP Form 11 (annual return)", authority="LLP", link="mca_portal", frequency="YEARLY",
         applies={"entities": ["LLP"]}, due={"dates": [{"month": 5, "day": 30}]},
         description="Annual return of the LLP.", penalty="Additional fee ₹100 per day of delay, with no upper limit."),
    dict(code="LLP8", name="LLP Form 8 (statement of accounts & solvency)", authority="LLP", link="mca_portal",
         frequency="YEARLY", applies={"entities": ["LLP"]}, due={"dates": [{"month": 10, "day": 30}]},
         description="Statement of account and solvency for the year.",
         penalty="Additional fee ₹100 per day of delay, with no upper limit."),
    # ------------------------------------------------------------------ payroll
    dict(code="PF", name="PF contribution and ECR", authority="PAYROLL", link="epfo_portal", frequency="MONTHLY",
         applies={"requires": ["payroll"]}, due={"months_after": 1, "day": 15},
         description="Employees' and employer's provident fund for the month's wages.",
         penalty="Interest 12% a year and damages of 5%–25% a year on late deposits."),
    dict(code="ESI", name="ESI contribution", authority="PAYROLL", link="esic_portal", frequency="MONTHLY",
         applies={"requires": ["payroll"]}, due={"months_after": 1, "day": 15},
         description="ESI contribution for the month's wages (if ESI applies to you).",
         penalty="Interest 12% a year and damages on late deposits."),
]
