"""Whole database as a plain PostgreSQL .sql file (data only) — for the platform administrator.

Load it into an EMPTY database that has the app's tables:
    1. create an empty PostgreSQL database
    2. cd backend && set DATABASE_URL=<that database> && alembic upgrade head
    3. psql "<that database>" -f gst-billing-YYYYMMDD-HHMM.sql
Generated by the app itself, so it needs no pg_dump on the server. Stored backups (they are backups of this same data)
and one-time sign-in codes are left out.
"""

import base64
import datetime as dt
import enum
import json
from decimal import Decimal

from sqlalchemy import JSON, select, text
from sqlalchemy.orm import Session

from ..db import Base
from .backup import SELF_REFS

EXCLUDE = {"platform_backups", "backups", "phone_otps"}
BATCH = 200


def _lit(col, v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float, Decimal)):
        return str(v)
    if isinstance(v, enum.Enum):
        v = v.value
    if isinstance(v, bytes):
        return f"decode('{base64.b64encode(v).decode()}', 'base64')"
    if isinstance(col.type, JSON) or isinstance(v, (dict, list)):
        return "'" + json.dumps(v, default=str).replace("'", "''") + "'::json"
    if isinstance(v, (dt.datetime, dt.date, dt.time)):
        return f"'{v.isoformat()}'"
    return "'" + str(v).replace("'", "''") + "'"


def dump(db: Session) -> bytes:
    try:
        rev = db.execute(text("select version_num from alembic_version")).scalar()
    except Exception:  # noqa: BLE001
        db.rollback()
        rev = None
    now = dt.datetime.now(dt.UTC)
    out = [f"-- GST billing database export (data only), {now:%Y-%m-%d %H:%M} UTC",
           f"-- Schema revision: {rev or 'unknown'} — run `alembic upgrade {rev or 'head'}` on an empty database first, then load this file.",
           "-- Stored backups and one-time codes are not included.", "", "BEGIN;", ""]
    counts = {}
    for t in Base.metadata.sorted_tables:
        if t.name in EXCLUDE:
            continue
        cols = list(t.c)
        later = SELF_REFS.get(t.name, [])
        rows = db.execute(select(t)).all()
        counts[t.name] = len(rows)
        if not rows:
            continue
        out.append(f"-- {t.name}: {len(rows)} rows")
        names = ", ".join(f'"{c.name}"' for c in cols)
        fixes = []
        for i in range(0, len(rows), BATCH):
            vals = []
            for r in rows[i:i + BATCH]:
                m = r._mapping
                vals.append("(" + ", ".join("NULL" if c.name in later else _lit(c, m[c.name]) for c in cols) + ")")
                for c in later:
                    if m[c] is not None:
                        fixes.append(f'UPDATE "{t.name}" SET "{c}" = {_lit(t.c[c], m[c])} WHERE "id" = {_lit(t.c["id"], m["id"])};')
            out.append(f'INSERT INTO "{t.name}" ({names}) VALUES\n' + ",\n".join(vals) + ";")
        out += fixes
        out.append("")
    out += ["COMMIT;", "", "-- rows per table: " + ", ".join(f"{k}={v}" for k, v in counts.items() if v)]
    return "\n".join(out).encode()


def filename() -> str:
    return f"gst-billing-database-{dt.datetime.now():%Y%m%d-%H%M}.sql"
