"""practitioner workspace

Revision ID: 15f232e57ac9
Revises: 6423c3e9e563
Create Date: 2026-09-27 22:48:19.203463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f232e57ac9'
down_revision: Union[str, Sequence[str], None] = '6423c3e9e563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_clients',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('nature_of_business', sa.String(length=200), nullable=True),
    sa.Column('linked_business_id', sa.String(length=32), nullable=True),
    sa.Column('mappings', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_clients_account_id'), 'practice_clients', ['account_id'], unique=False)
    op.create_table('practice_files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('fy', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='DRAFT', nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('final_snapshot', sa.JSON(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['practice_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'fy', name='uq_practice_file_fy')
    )
    op.create_index(op.f('ix_practice_files_client_id'), 'practice_files', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_files_client_id'), table_name='practice_files')
    op.drop_table('practice_files')
    op.drop_index(op.f('ix_practice_clients_account_id'), table_name='practice_clients')
    op.drop_table('practice_clients')
    # ### end Alembic commands ###
