"""consent, privacy requests, incidents

Revision ID: 335a1e2ff451
Revises: 0132664833f8
Create Date: 2026-10-10 10:07:17.615274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335a1e2ff451'
down_revision: Union[str, Sequence[str], None] = '0132664833f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_incidents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected', sa.Text(), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('user_email', sa.String(length=200), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('business_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('handled_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_requests_created_at'), 'data_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_requests_user_id'), 'data_requests', ['user_id'], unique=False)
    op.create_table('legal_acceptances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_acceptances_user_id'), 'legal_acceptances', ['user_id'], unique=False)
    op.add_column('users', sa.Column('legal_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'legal_version')
    op.drop_index(op.f('ix_legal_acceptances_user_id'), table_name='legal_acceptances')
    op.drop_table('legal_acceptances')
    op.drop_index(op.f('ix_data_requests_user_id'), table_name='data_requests')
    op.drop_index(op.f('ix_data_requests_created_at'), table_name='data_requests')
    op.drop_table('data_requests')
    op.drop_table('security_incidents')
    # ### end Alembic commands ###
