"""site pages

Revision ID: 441c704031fc
Revises: 4cf0605a9131
Create Date: 2026-10-10 16:12:25.951976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441c704031fc'
down_revision: Union[str, Sequence[str], None] = '4cf0605a9131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_page_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('saved_by', sa.String(length=120), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_page_versions_slug'), 'site_page_versions', ['slug'], unique=False)
    op.create_table('site_pages',
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_pages')
    op.drop_index(op.f('ix_site_page_versions_slug'), table_name='site_page_versions')
    op.drop_table('site_page_versions')
    # ### end Alembic commands ###
