"""payment reminders

Revision ID: 4c0a00fa858b
Revises: 15f232e57ac9
Create Date: 2026-10-06 16:25:11.041951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0a00fa858b'
down_revision: Union[str, Sequence[str], None] = '15f232e57ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('party_id', sa.String(length=32), nullable=True),
    sa.Column('voucher_id', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('sent_to', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('automatic', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('by_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_logs_business_id'), 'reminder_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_reminder_logs_created_at'), 'reminder_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_reminder_logs_party_id'), 'reminder_logs', ['party_id'], unique=False)
    op.create_index(op.f('ix_reminder_logs_voucher_id'), 'reminder_logs', ['voucher_id'], unique=False)
    op.add_column('businesses', sa.Column('reminder_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'reminder_settings')
    op.drop_index(op.f('ix_reminder_logs_voucher_id'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_party_id'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_created_at'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_business_id'), table_name='reminder_logs')
    op.drop_table('reminder_logs')
    # ### end Alembic commands ###
