"""ewb api user, einvoice applicable

Revision ID: 5b51fa183795
Revises: cabc31bb4b71
Create Date: 2026-10-07 18:34:37.176020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b51fa183795'
down_revision: Union[str, Sequence[str], None] = 'cabc31bb4b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('ewb_username', sa.String(length=100), nullable=True))
    op.add_column('businesses', sa.Column('ewb_password_enc', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('einvoice_applicable', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'einvoice_applicable')
    op.drop_column('businesses', 'ewb_password_enc')
    op.drop_column('businesses', 'ewb_username')
    # ### end Alembic commands ###
