"""business entity type, modules, compliance settings

Revision ID: 865e6487691d
Revises: 271cec1a913b
Create Date: 2026-10-06 21:39:10.711986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865e6487691d'
down_revision: Union[str, Sequence[str], None] = '271cec1a913b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('entity_type', sa.String(length=20), server_default='PROPRIETORSHIP', nullable=False))
    op.add_column('businesses', sa.Column('modules', sa.JSON(), nullable=True))
    op.add_column('businesses', sa.Column('compliance_settings', sa.JSON(), nullable=True))
    # best guess for existing businesses from the PAN's 4th letter (and the name for LLPs); owners can change it
    op.execute("""
        UPDATE businesses SET entity_type = CASE
            WHEN upper(coalesce(legal_name, name)) LIKE '%LLP%' THEN 'LLP'
            WHEN substr(upper(pan), 4, 1) = 'C' THEN
                CASE WHEN upper(coalesce(legal_name, name)) LIKE '%OPC%' THEN 'OPC' ELSE 'PRIVATE_LIMITED' END
            WHEN substr(upper(pan), 4, 1) = 'F' THEN 'PARTNERSHIP'
            WHEN substr(upper(pan), 4, 1) = 'H' THEN 'HUF'
            WHEN substr(upper(pan), 4, 1) IN ('T', 'A') THEN 'TRUST_SOCIETY'
            ELSE 'PROPRIETORSHIP' END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'compliance_settings')
    op.drop_column('businesses', 'modules')
    op.drop_column('businesses', 'entity_type')
    # ### end Alembic commands ###
