"""gst return status from portal

Revision ID: 98072a70ed95
Revises: 4daf4833fc64
Create Date: 2026-10-06 23:57:31.891550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98072a70ed95'
down_revision: Union[str, Sequence[str], None] = '4daf4833fc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gst_return_status',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('fy', sa.String(length=7), nullable=False),
    sa.Column('return_type', sa.String(length=20), nullable=False),
    sa.Column('return_period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('filed', sa.Boolean(), nullable=False),
    sa.Column('filed_on', sa.Date(), nullable=True),
    sa.Column('arn', sa.String(length=30), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_return_status_business_id'), 'gst_return_status', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gst_return_status_business_id'), table_name='gst_return_status')
    op.drop_table('gst_return_status')
    # ### end Alembic commands ###
