"""compliance filing source

Revision ID: abfa04b1f27c
Revises: c91c9e349ac4
Create Date: 2026-10-06 23:16:25.501096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abfa04b1f27c'
down_revision: Union[str, Sequence[str], None] = 'c91c9e349ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_filings', sa.Column('source', sa.String(length=10), server_default='MANUAL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compliance_filings', 'source')
    # ### end Alembic commands ###
