"""whatsapp sandbox preview

Revision ID: b2891f589a4a
Revises: 62a72f1d20c5
Create Date: 2026-10-08 23:09:41.686790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2891f589a4a'
down_revision: Union[str, Sequence[str], None] = '62a72f1d20c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_messages', sa.Column('preview', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_messages', 'preview')
    # ### end Alembic commands ###
