"""staff attendance payroll

Revision ID: b546ab9b8678
Revises: 24ca9770e7d8
Create Date: 2026-10-08 00:04:35.165916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b546ab9b8678'
down_revision: Union[str, Sequence[str], None] = '24ca9770e7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('designation', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('left_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('salary_type', sa.String(length=8), nullable=False),
    sa.Column('salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('basic_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ot_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pf', sa.Boolean(), nullable=False),
    sa.Column('esi', sa.Boolean(), nullable=False),
    sa.Column('pt_monthly', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tds_monthly', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('uan', sa.String(length=20), nullable=True),
    sa.Column('esic_no', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('bank_account', sa.String(length=40), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=11), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_business_id'), 'employees', ['business_id'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=2), nullable=False),
    sa.Column('check_in', sa.String(length=5), nullable=True),
    sa.Column('check_out', sa.String(length=5), nullable=True),
    sa.Column('ot_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=6), nullable=False),
    sa.Column('marked_by', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_attendance_day')
    )
    op.create_index(op.f('ix_attendance_business_id'), 'attendance', ['business_id'], unique=False)
    op.create_index(op.f('ix_attendance_date'), 'attendance', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=6), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('voucher_id', sa.String(length=32), nullable=True),
    sa.Column('statutory_paid', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'month', name='uq_payroll_month')
    )
    op.create_index(op.f('ix_payroll_runs_business_id'), 'payroll_runs', ['business_id'], unique=False)
    op.create_table('salary_advances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('voucher_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_advances_business_id'), 'salary_advances', ['business_id'], unique=False)
    op.create_index(op.f('ix_salary_advances_employee_id'), 'salary_advances', ['employee_id'], unique=False)
    op.create_table('payroll_lines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_additions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('advance_recovery', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_lines_employee_id'), 'payroll_lines', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_lines_run_id'), 'payroll_lines', ['run_id'], unique=False)
    op.add_column('businesses', sa.Column('payroll_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'payroll_settings')
    op.drop_index(op.f('ix_payroll_lines_run_id'), table_name='payroll_lines')
    op.drop_index(op.f('ix_payroll_lines_employee_id'), table_name='payroll_lines')
    op.drop_table('payroll_lines')
    op.drop_index(op.f('ix_salary_advances_employee_id'), table_name='salary_advances')
    op.drop_index(op.f('ix_salary_advances_business_id'), table_name='salary_advances')
    op.drop_table('salary_advances')
    op.drop_index(op.f('ix_payroll_runs_business_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_date'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_business_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_business_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
