"""stock control

Revision ID: b9a807529662
Revises: 5b51fa183795
Create Date: 2026-10-07 23:26:18.453441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a807529662'
down_revision: Union[str, Sequence[str], None] = '5b51fa183795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('stock_control', sa.String(length=5), server_default='WARN', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'stock_control')
    # ### end Alembic commands ###
