"""manufacturing

Revision ID: bdabe8b6dada
Revises: 8062c62e6368
Create Date: 2026-10-06 18:05:24.804168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdabe8b6dada'
down_revision: Union[str, Sequence[str], None] = '8062c62e6368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('output_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('other_cost', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boms_business_id'), 'boms', ['business_id'], unique=False)
    op.create_index(op.f('ix_boms_item_id'), 'boms', ['item_id'], unique=False)
    op.create_table('bom_lines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('bom_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_lines_bom_id'), 'bom_lines', ['bom_id'], unique=False)
    op.create_table('productions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bom_id', sa.String(length=32), nullable=True),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('godown_id', sa.String(length=32), nullable=True),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('material_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('consumed', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productions_business_id'), 'productions', ['business_id'], unique=False)
    op.create_index(op.f('ix_productions_date'), 'productions', ['date'], unique=False)
    op.add_column('stock_movements', sa.Column('production_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_stock_movements_production_id'), 'stock_movements', ['production_id'], unique=False)
    op.create_foreign_key(None, 'stock_movements', 'productions', ['production_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_production_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'production_id')
    op.drop_index(op.f('ix_productions_date'), table_name='productions')
    op.drop_index(op.f('ix_productions_business_id'), table_name='productions')
    op.drop_table('productions')
    op.drop_index(op.f('ix_bom_lines_bom_id'), table_name='bom_lines')
    op.drop_table('bom_lines')
    op.drop_index(op.f('ix_boms_item_id'), table_name='boms')
    op.drop_index(op.f('ix_boms_business_id'), table_name='boms')
    op.drop_table('boms')
    # ### end Alembic commands ###
