"""exports lut composition itc blocked

Revision ID: fecf59b410a1
Revises: 58b93fd87235
Create Date: 2026-09-25 12:43:21.288282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fecf59b410a1'
down_revision: Union[str, Sequence[str], None] = '58b93fd87235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('lut_number', sa.String(length=30), nullable=True))
    op.add_column('businesses', sa.Column('lut_valid_till', sa.Date(), nullable=True))
    op.add_column('businesses', sa.Column('composition_type', sa.String(length=12), server_default='TRADER', nullable=False))
    op.add_column('expense_categories', sa.Column('itc_blocked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('vouchers', sa.Column('export_type', sa.String(length=8), nullable=True))
    op.add_column('vouchers', sa.Column('shipping_bill_no', sa.String(length=20), nullable=True))
    op.add_column('vouchers', sa.Column('shipping_bill_date', sa.Date(), nullable=True))
    op.add_column('vouchers', sa.Column('port_code', sa.String(length=10), nullable=True))
    op.add_column('vouchers', sa.Column('currency_code', sa.String(length=3), nullable=True))
    op.add_column('vouchers', sa.Column('exchange_rate', sa.Numeric(precision=12, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vouchers', 'exchange_rate')
    op.drop_column('vouchers', 'currency_code')
    op.drop_column('vouchers', 'port_code')
    op.drop_column('vouchers', 'shipping_bill_date')
    op.drop_column('vouchers', 'shipping_bill_no')
    op.drop_column('vouchers', 'export_type')
    op.drop_column('expense_categories', 'itc_blocked')
    op.drop_column('businesses', 'composition_type')
    op.drop_column('businesses', 'lut_valid_till')
    op.drop_column('businesses', 'lut_number')
    # ### end Alembic commands ###
