"""audit changes edit log

Revision ID: 0132664833f8
Revises: 0aae138f578f
Create Date: 2026-10-10 09:53:33.872555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0132664833f8'
down_revision: Union[str, Sequence[str], None] = '0aae138f578f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_changes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=True),
    sa.Column('table_name', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('row_id', sa.String(length=32), nullable=True),
    sa.Column('op', sa.String(length=6), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_changes_business_at', 'audit_changes', ['business_id', 'at'], unique=False)
    op.create_index('ix_audit_changes_row', 'audit_changes', ['row_id'], unique=False)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        # the audit trail cannot be changed or deleted (see app/services/edit_log.py)
        from app.services.edit_log import _FN, _trigger

        op.execute(str(_FN.statement))
        for t in ("audit_logs", "audit_changes"):
            op.execute(str(_trigger(t).statement))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_changes_row', table_name='audit_changes')
    op.drop_index('ix_audit_changes_business_at', table_name='audit_changes')
    op.drop_table('audit_changes')
    # ### end Alembic commands ###
