"""api credits

Revision ID: 1fc89a16af9b
Revises: b546ab9b8678
Create Date: 2026-10-08 17:04:10.069648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc89a16af9b'
down_revision: Union[str, Sequence[str], None] = 'b546ab9b8678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_credits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=6), nullable=False),
    sa.Column('action', sa.String(length=15), nullable=True),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('from_pack', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_credits_account_id'), 'api_credits', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_credits_created_at'), 'api_credits', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_credits_created_at'), table_name='api_credits')
    op.drop_index(op.f('ix_api_credits_account_id'), table_name='api_credits')
    op.drop_table('api_credits')
    # ### end Alembic commands ###
