"""filing sync per business

Revision ID: 263f5dbdad0c
Revises: 4b99f69229b8
Create Date: 2026-10-09 16:24:38.418733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263f5dbdad0c'
down_revision: Union[str, Sequence[str], None] = '4b99f69229b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('filing_sync', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'filing_sync')
    # ### end Alembic commands ###
