"""business certificates

Revision ID: 4b60748dface
Revises: 263f5dbdad0c
Create Date: 2026-10-09 17:59:18.295404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b60748dface'
down_revision: Union[str, Sequence[str], None] = '263f5dbdad0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_certificates',
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('pfx_enc', sa.Text(), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('organisation', sa.String(length=200), nullable=True),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('serial', sa.String(length=64), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('uploaded_by', sa.String(length=120), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_certificates')
    # ### end Alembic commands ###
