"""excel backup per business

Revision ID: 4b99f69229b8
Revises: b2891f589a4a
Create Date: 2026-10-09 09:22:18.082807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b99f69229b8'
down_revision: Union[str, Sequence[str], None] = 'b2891f589a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('excel_backup', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'excel_backup')
    # ### end Alembic commands ###
