"""analytics: visits, events, module usage

Revision ID: 4c0c7593d811
Revises: dccf89b35111
Create Date: 2026-10-10 18:16:27.545900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0c7593d811'
down_revision: Union[str, Sequence[str], None] = 'dccf89b35111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('visitor', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=30), nullable=True),
    sa.Column('cycle', sa.String(length=12), nullable=True),
    sa.Column('page', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_events_day'), 'site_events', ['day'], unique=False)
    op.create_index(op.f('ix_site_events_user_id'), 'site_events', ['user_id'], unique=False)
    op.create_table('site_visits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('visitor', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('referrer', sa.String(length=120), nullable=True),
    sa.Column('utm_source', sa.String(length=60), nullable=True),
    sa.Column('utm_campaign', sa.String(length=60), nullable=True),
    sa.Column('device', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_visits_day'), 'site_visits', ['day'], unique=False)
    op.create_index(op.f('ix_site_visits_visitor'), 'site_visits', ['visitor'], unique=False)
    op.create_table('module_usage',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('last_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'user_id', 'business_id', 'module', name='uq_module_usage')
    )
    op.create_index(op.f('ix_module_usage_day'), 'module_usage', ['day'], unique=False)
    op.create_index(op.f('ix_module_usage_user_id'), 'module_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_module_usage_user_id'), table_name='module_usage')
    op.drop_index(op.f('ix_module_usage_day'), table_name='module_usage')
    op.drop_table('module_usage')
    op.drop_index(op.f('ix_site_visits_visitor'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_day'), table_name='site_visits')
    op.drop_table('site_visits')
    op.drop_index(op.f('ix_site_events_user_id'), table_name='site_events')
    op.drop_index(op.f('ix_site_events_day'), table_name='site_events')
    op.drop_table('site_events')
    # ### end Alembic commands ###
