"""mail senders

Revision ID: 4cf0605a9131
Revises: 335a1e2ff451
Create Date: 2026-10-10 16:00:33.526850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf0605a9131'
down_revision: Union[str, Sequence[str], None] = '335a1e2ff451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_senders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=10), nullable=False),
    sa.Column('secret_enc', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=5), nullable=True),
    sa.Column('host', sa.String(length=200), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('security', sa.String(length=10), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('from_email', sa.String(length=200), nullable=False),
    sa.Column('from_name', sa.String(length=120), nullable=True),
    sa.Column('reply_to', sa.String(length=200), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('businesses', sa.Column('mail_sender_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'businesses', 'mail_senders', ['mail_sender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'mail_sender_id')
    op.drop_table('mail_senders')
    # ### end Alembic commands ###
