"""payment records, notifications, platform team

Revision ID: 55f0b527174b
Revises: 60f73b5a42e6
Create Date: 2026-10-10 17:44:14.557452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f0b527174b'
down_revision: Union[str, Sequence[str], None] = '60f73b5a42e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('subscription_payments', sa.Column('business_id', sa.String(length=32), nullable=True))
    op.add_column('subscription_payments', sa.Column('user_id', sa.String(length=32), nullable=True))
    op.add_column('subscription_payments', sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('subscription_payments', sa.Column('error_code', sa.String(length=60), nullable=True))
    op.add_column('subscription_payments', sa.Column('error_reason', sa.String(length=300), nullable=True))
    op.add_column('subscription_payments', sa.Column('receipt_no', sa.String(length=20), nullable=True))
    op.add_column('subscription_payments', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscription_payments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_subscription_payments_created_at'), 'subscription_payments', ['created_at'], unique=False)
    op.create_unique_constraint('uq_subscription_payments_receipt_no', 'subscription_payments', ['receipt_no'])
    # earlier paid payments: paid time and a receipt number, in date order within each financial year
    conn = op.get_bind()
    counters: dict[str, int] = {}
    for pid, created in conn.execute(sa.text("SELECT id, created_at FROM subscription_payments WHERE status = 'PAID' ORDER BY created_at")).all():
        fy = created.year if created.month >= 4 else created.year - 1
        prefix = f"SR{str(fy)[2:]}{str(fy + 1)[2:]}-"
        counters[prefix] = counters.get(prefix, 0) + 1
        conn.execute(sa.text("UPDATE subscription_payments SET paid_at = created_at, receipt_no = :r WHERE id = :i"),
                     {"r": f"{prefix}{counters[prefix]:05d}", "i": pid})
    op.add_column('users', sa.Column('platform_areas', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('platform_team', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'platform_team')
    op.drop_column('users', 'platform_areas')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_subscription_payments_receipt_no', 'subscription_payments', type_='unique')
    op.drop_index(op.f('ix_subscription_payments_created_at'), table_name='subscription_payments')
    op.drop_column('subscription_payments', 'updated_at')
    op.drop_column('subscription_payments', 'paid_at')
    op.drop_column('subscription_payments', 'receipt_no')
    op.drop_column('subscription_payments', 'error_reason')
    op.drop_column('subscription_payments', 'error_code')
    op.drop_column('subscription_payments', 'gst_rate')
    op.drop_column('subscription_payments', 'user_id')
    op.drop_column('subscription_payments', 'business_id')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
