"""whatsapp otp and messages

Revision ID: 62a72f1d20c5
Revises: 1fc89a16af9b
Create Date: 2026-10-08 22:33:06.169284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a72f1d20c5'
down_revision: Union[str, Sequence[str], None] = '1fc89a16af9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_otps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('purpose', sa.String(length=8), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_otps_created_at'), 'phone_otps', ['created_at'], unique=False)
    op.create_index(op.f('ix_phone_otps_ip'), 'phone_otps', ['ip'], unique=False)
    op.create_index(op.f('ix_phone_otps_phone'), 'phone_otps', ['phone'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=True),
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('to', sa.String(length=15), nullable=False),
    sa.Column('template', sa.String(length=80), nullable=True),
    sa.Column('wamid', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('ref', sa.String(length=64), nullable=True),
    sa.Column('by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_account_id'), 'whatsapp_messages', ['account_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_business_id'), 'whatsapp_messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_created_at'), 'whatsapp_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_wamid'), 'whatsapp_messages', ['wamid'], unique=False)
    op.add_column('users', sa.Column('mobile', sa.String(length=12), nullable=True))
    op.add_column('users', sa.Column('mobile_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_column('users', 'mobile_verified_at')
    op.drop_column('users', 'mobile')
    op.drop_index(op.f('ix_whatsapp_messages_wamid'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_created_at'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_business_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_account_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_phone_otps_phone'), table_name='phone_otps')
    op.drop_index(op.f('ix_phone_otps_ip'), table_name='phone_otps')
    op.drop_index(op.f('ix_phone_otps_created_at'), table_name='phone_otps')
    op.drop_table('phone_otps')
    # ### end Alembic commands ###
