"""subscription payment mode and method

Revision ID: 6423c3e9e563
Revises: 7391882113cf
Create Date: 2026-09-25 22:23:18.136050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6423c3e9e563'
down_revision: Union[str, Sequence[str], None] = '7391882113cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_payments', sa.Column('mode', sa.String(length=4), nullable=True))
    op.add_column('subscription_payments', sa.Column('method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_payments', 'method')
    op.drop_column('subscription_payments', 'mode')
    # ### end Alembic commands ###
