"""gstin account, temp password, previous login

Revision ID: 7391882113cf
Revises: f53cbbf2a5ec
Create Date: 2026-09-25 20:00:38.918063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7391882113cf'
down_revision: Union[str, Sequence[str], None] = 'f53cbbf2a5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gstin_lookups', sa.Column('account_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_gstin_lookups_account_id'), 'gstin_lookups', ['account_id'], unique=False)
    op.add_column('password_resets', sa.Column('temp_hash', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('previous_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'previous_login_at')
    op.drop_column('password_resets', 'temp_hash')
    op.drop_index(op.f('ix_gstin_lookups_account_id'), table_name='gstin_lookups')
    op.drop_column('gstin_lookups', 'account_id')
    # ### end Alembic commands ###
