"""price lists

Revision ID: 8062c62e6368
Revises: cbc4ac6c3269
Create Date: 2026-10-06 17:55:02.883882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8062c62e6368'
down_revision: Union[str, Sequence[str], None] = 'cbc4ac6c3269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_lists',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('based_on', sa.String(length=12), server_default='SALE_PRICE', nullable=False),
    sa.Column('adjust_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_lists_business_id'), 'price_lists', ['business_id'], unique=False)
    op.create_table('price_list_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('price_list_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_list_id', 'item_id', name='uq_price_list_item')
    )
    op.create_index(op.f('ix_price_list_items_item_id'), 'price_list_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_price_list_items_price_list_id'), 'price_list_items', ['price_list_id'], unique=False)
    op.add_column('parties', sa.Column('price_list_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'parties', 'price_lists', ['price_list_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'parties', type_='foreignkey')
    op.drop_column('parties', 'price_list_id')
    op.drop_index(op.f('ix_price_list_items_price_list_id'), table_name='price_list_items')
    op.drop_index(op.f('ix_price_list_items_item_id'), table_name='price_list_items')
    op.drop_table('price_list_items')
    op.drop_index(op.f('ix_price_lists_business_id'), table_name='price_lists')
    op.drop_table('price_lists')
    # ### end Alembic commands ###
