"""business expense setup choice

Revision ID: 921b680c37e2
Revises: 4c0c7593d811
Create Date: 2026-10-10 22:28:47.543948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921b680c37e2'
down_revision: Union[str, Sequence[str], None] = '4c0c7593d811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('expense_setup', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'expense_setup')
    # ### end Alembic commands ###
