"""gst registration date

Revision ID: a7c85b32b322
Revises: 98072a70ed95
Create Date: 2026-10-07 00:18:57.951978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c85b32b322'
down_revision: Union[str, Sequence[str], None] = '98072a70ed95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('gst_registration_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'gst_registration_date')
    # ### end Alembic commands ###
