"""platform config hsn master rate notices

Revision ID: aa4b7a2c2965
Revises: fecf59b410a1
Create Date: 2026-09-25 14:54:14.633888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4b7a2c2965'
down_revision: Union[str, Sequence[str], None] = 'fecf59b410a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_hsn',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('rate_notices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_notice_actions',
    sa.Column('notice_id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('items_changed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('by_name', sa.String(length=200), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notice_id'], ['rate_notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notice_id', 'business_id')
    )
    op.alter_column('payments', 'number',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('stock_transfers', 'number',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('vouchers', 'number',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vouchers', 'number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('stock_transfers', 'number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('payments', 'number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_table('rate_notice_actions')
    op.drop_table('rate_notices')
    op.drop_table('master_hsn')
    # ### end Alembic commands ###
