"""offline bills client ref

Revision ID: b420b82613c6
Revises: bdabe8b6dada
Create Date: 2026-10-06 18:11:05.315807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b420b82613c6'
down_revision: Union[str, Sequence[str], None] = 'bdabe8b6dada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vouchers', sa.Column('client_ref', sa.String(length=40), nullable=True))
    op.create_unique_constraint('uq_voucher_client_ref', 'vouchers', ['business_id', 'client_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_voucher_client_ref', 'vouchers', type_='unique')
    op.drop_column('vouchers', 'client_ref')
    # ### end Alembic commands ###
