"""hsn master optional rate and code requests

Revision ID: b5195bcb8dd1
Revises: aa4b7a2c2965
Create Date: 2026-09-25 17:43:33.903848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5195bcb8dd1'
down_revision: Union[str, Sequence[str], None] = 'aa4b7a2c2965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hsn_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='PENDING', nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hsn_requests_business_id'), 'hsn_requests', ['business_id'], unique=False)
    op.alter_column('master_hsn', 'gst_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('master_hsn', 'gst_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_hsn_requests_business_id'), table_name='hsn_requests')
    op.drop_table('hsn_requests')
    # ### end Alembic commands ###
