"""staff logins, invitations, sign-in control

Revision ID: c91c9e349ac4
Revises: f14c03e44cf7
Create Date: 2026-10-06 22:51:30.707702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91c9e349ac4'
down_revision: Union[str, Sequence[str], None] = 'f14c03e44cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'user_id', 'sid', name='uq_staff_session')
    )
    op.create_index(op.f('ix_staff_sessions_business_id'), 'staff_sessions', ['business_id'], unique=False)
    op.create_index(op.f('ix_staff_sessions_user_id'), 'staff_sessions', ['user_id'], unique=False)
    op.add_column('businesses', sa.Column('staff_access', sa.JSON(), nullable=True))
    op.add_column('memberships', sa.Column('status', sa.String(length=10), server_default='ACTIVE', nullable=False))
    op.add_column('memberships', sa.Column('invited_by', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('created_by_business_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_by_business_id')
    op.drop_column('memberships', 'invited_by')
    op.drop_column('memberships', 'status')
    op.drop_column('businesses', 'staff_access')
    op.drop_index(op.f('ix_staff_sessions_user_id'), table_name='staff_sessions')
    op.drop_index(op.f('ix_staff_sessions_business_id'), table_name='staff_sessions')
    op.drop_table('staff_sessions')
    # ### end Alembic commands ###
