"""initial schema

Revision ID: c9fc521dcacc
Revises: 
Create Date: 2026-09-25 09:18:12.677470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fc521dcacc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('platform_role', sa.String(length=12), nullable=True),
    sa.Column('reseller_commission_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('businesses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('gst_type', sa.Enum('REGULAR', 'COMPOSITION', 'UNREGISTERED', name='businessgsttype', native_enum=False, length=20), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('bank_account_no', sa.String(length=40), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=11), nullable=True),
    sa.Column('bank_branch', sa.String(length=120), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=8), nullable=False),
    sa.Column('credit_note_prefix', sa.String(length=8), nullable=False),
    sa.Column('debit_note_prefix', sa.String(length=8), nullable=False),
    sa.Column('estimate_prefix', sa.String(length=8), nullable=False),
    sa.Column('purchase_prefix', sa.String(length=8), nullable=False),
    sa.Column('receipt_prefix', sa.String(length=8), nullable=False),
    sa.Column('payment_prefix', sa.String(length=8), nullable=False),
    sa.Column('challan_prefix', sa.String(length=8), nullable=False),
    sa.Column('sale_order_prefix', sa.String(length=8), nullable=False),
    sa.Column('purchase_order_prefix', sa.String(length=8), nullable=False),
    sa.Column('expense_prefix', sa.String(length=8), nullable=False),
    sa.Column('invoice_terms', sa.Text(), nullable=True),
    sa.Column('auto_backup', sa.Boolean(), nullable=False),
    sa.Column('backup_email', sa.String(length=200), nullable=True),
    sa.Column('transfer_prefix', sa.String(length=8), nullable=False),
    sa.Column('print_settings', sa.JSON(), nullable=True),
    sa.Column('einvoice_username', sa.String(length=100), nullable=True),
    sa.Column('einvoice_password_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_owner_id'), 'businesses', ['owner_id'], unique=False)
    op.create_table('license_sales',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('reseller_id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payout_status', sa.String(length=10), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reseller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_sales_reseller_id'), 'license_sales', ['reseller_id'], unique=False)
    op.create_table('subscription_payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('cycle', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('order_id', sa.String(length=60), nullable=False),
    sa.Column('payment_id', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_subscription_payments_account_id'), 'subscription_payments', ['account_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('extra_businesses', sa.Integer(), nullable=False),
    sa.Column('feature_flags', sa.JSON(), nullable=True),
    sa.Column('reseller_id', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reseller_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_subscriptions_reseller_id'), 'subscriptions', ['reseller_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('CASH', 'BANK', name='accounttype', native_enum=False, length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('account_no', sa.String(length=40), nullable=True),
    sa.Column('ifsc', sa.String(length=11), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('is_default_cash', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_business_id'), 'accounts', ['business_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_business_created', 'audit_logs', ['business_id', 'created_at'], unique=False)
    op.create_table('backups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('emailed_to', sa.String(length=200), nullable=True),
    sa.Column('created_by_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_business_id'), 'backups', ['business_id'], unique=False)
    op.create_table('counters',
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('fy', sa.String(length=7), nullable=False),
    sa.Column('next', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id', 'key', 'fy')
    )
    op.create_table('expense_categories',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('DIRECT', 'INDIRECT', name='expensekind', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_expense_category')
    )
    op.create_index(op.f('ix_expense_categories_business_id'), 'expense_categories', ['business_id'], unique=False)
    op.create_table('godowns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_godowns_business_id'), 'godowns', ['business_id'], unique=False)
    op.create_table('hsn_codes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'code', name='uq_hsn_code')
    )
    op.create_index(op.f('ix_hsn_codes_business_id'), 'hsn_codes', ['business_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('GOODS', 'SERVICE', name='itemtype', native_enum=False, length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('hsn_sac', sa.String(length=8), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sale_price_tax_inclusive', sa.Boolean(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purchase_price_tax_inclusive', sa.Boolean(), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('low_stock_level', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('track_batch', sa.Boolean(), nullable=False),
    sa.Column('track_serial', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_items_business_name', 'items', ['business_id', 'name'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lender', sa.String(length=120), nullable=True),
    sa.Column('account_no', sa.String(length=40), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_business_id'), 'loans', ['business_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'BILLING', 'INVENTORY', 'ACCOUNTANT', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('approval_pin_hash', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'business_id')
    )
    op.create_index(op.f('ix_memberships_business_id'), 'memberships', ['business_id'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('CUSTOMER', 'SUPPLIER', 'BOTH', name='partytype', native_enum=False, length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gst_type', sa.Enum('REGISTERED', 'COMPOSITION', 'UNREGISTERED', 'CONSUMER', 'SEZ', 'OVERSEAS', name='partygsttype', native_enum=False, length=20), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parties_business_name', 'parties', ['business_id', 'name'], unique=False)
    op.create_table('account_transfers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('from_account_id', sa.String(length=32), nullable=False),
    sa.Column('to_account_id', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_transfers_business_id'), 'account_transfers', ['business_id'], unique=False)
    op.create_table('capital_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('INTRODUCED', 'DRAWINGS', name='capitaltype', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capital_entries_business_id'), 'capital_entries', ['business_id'], unique=False)
    op.create_table('expense_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hsn_sac', sa.String(length=8), nullable=True),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_expense_item')
    )
    op.create_index(op.f('ix_expense_items_business_id'), 'expense_items', ['business_id'], unique=False)
    op.create_table('loan_txns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('loan_id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('DISBURSEMENT', 'EMI', 'CHARGES', name='loantxntype', native_enum=False, length=20), nullable=False),
    sa.Column('principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_txns_business_id'), 'loan_txns', ['business_id'], unique=False)
    op.create_index(op.f('ix_loan_txns_loan_id'), 'loan_txns', ['loan_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('IN', 'OUT', name='paymenttype', native_enum=False, length=20), nullable=False),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('party_id', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.Enum('CASH', 'BANK', 'UPI', 'CHEQUE', 'CARD', 'OTHER', name='paymentmode', native_enum=False, length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cheque_status', sa.String(length=10), nullable=True),
    sa.Column('cheque_date', sa.Date(), nullable=True),
    sa.Column('cleared_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'type', 'number', name='uq_payment_number')
    )
    op.create_index(op.f('ix_payments_account_id'), 'payments', ['account_id'], unique=False)
    op.create_index('ix_payments_business_date', 'payments', ['business_id', 'date'], unique=False)
    op.create_index(op.f('ix_payments_party_id'), 'payments', ['party_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('from_godown_id', sa.String(length=32), nullable=False),
    sa.Column('to_godown_id', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_godown_id'], ['godowns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_godown_id'], ['godowns.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfers_business_id'), 'stock_transfers', ['business_id'], unique=False)
    op.create_table('tax_payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('GST', 'TDS', 'TCS', name='taxpaymenttype', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_payments_business_id'), 'tax_payments', ['business_id'], unique=False)
    op.create_table('vouchers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('SALE', 'SALE_RETURN', 'PURCHASE', 'PURCHASE_RETURN', 'ESTIMATE', 'DELIVERY_CHALLAN', 'SALE_ORDER', 'PURCHASE_ORDER', 'EXPENSE', name='vouchertype', native_enum=False, length=20), nullable=False),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('party_id', sa.String(length=32), nullable=True),
    sa.Column('party_name', sa.String(length=200), nullable=False),
    sa.Column('party_gstin', sa.String(length=15), nullable=True),
    sa.Column('party_state_code', sa.String(length=2), nullable=True),
    sa.Column('party_address', sa.Text(), nullable=True),
    sa.Column('party_phone', sa.String(length=20), nullable=True),
    sa.Column('place_of_supply', sa.String(length=2), nullable=False),
    sa.Column('inter_state', sa.Boolean(), nullable=False),
    sa.Column('tax_applicable', sa.Boolean(), nullable=False),
    sa.Column('reverse_charge', sa.Boolean(), nullable=False),
    sa.Column('supplier_invoice_no', sa.String(length=50), nullable=True),
    sa.Column('supplier_invoice_date', sa.Date(), nullable=True),
    sa.Column('original_voucher_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('expense_category_id', sa.String(length=32), nullable=True),
    sa.Column('source_voucher_id', sa.String(length=32), nullable=True),
    sa.Column('godown_id', sa.String(length=32), nullable=True),
    sa.Column('transport', sa.JSON(), nullable=True),
    sa.Column('extra_fields', sa.JSON(), nullable=True),
    sa.Column('irn', sa.String(length=64), nullable=True),
    sa.Column('ack_no', sa.String(length=20), nullable=True),
    sa.Column('ack_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_qr', sa.Text(), nullable=True),
    sa.Column('einvoice_status', sa.String(length=12), nullable=True),
    sa.Column('einvoice_sandbox', sa.Boolean(), nullable=False),
    sa.Column('ewb_no', sa.String(length=20), nullable=True),
    sa.Column('ewb_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ewb_valid_till', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sub_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cess', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tcs_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tcs_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('converted_to_id', sa.String(length=32), nullable=True),
    sa.Column('created_by_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['original_voucher_id'], ['vouchers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'type', 'number', name='uq_voucher_number')
    )
    op.create_index('ix_vouchers_business_type_date', 'vouchers', ['business_id', 'type', 'date'], unique=False)
    op.create_index('ix_vouchers_party', 'vouchers', ['party_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('payment_id', sa.String(length=32), nullable=False),
    sa.Column('voucher_id', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_voucher_id'), 'payment_allocations', ['voucher_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('OPENING', 'SALE', 'SALE_RETURN', 'PURCHASE', 'PURCHASE_RETURN', 'ADJUSTMENT', 'TRANSFER', name='stockmovetype', native_enum=False, length=20), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('godown_id', sa.String(length=32), nullable=True),
    sa.Column('transfer_id', sa.String(length=32), nullable=True),
    sa.Column('voucher_id', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['godown_id'], ['godowns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_business_item_date', 'stock_movements', ['business_id', 'item_id', 'date'], unique=False)
    op.create_index(op.f('ix_stock_movements_godown_id'), 'stock_movements', ['godown_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_transfer_id'), 'stock_movements', ['transfer_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_voucher_id'), 'stock_movements', ['voucher_id'], unique=False)
    op.create_table('voucher_lines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('voucher_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=True),
    sa.Column('expense_item_id', sa.String(length=32), nullable=True),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('mfg_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('serial_nos', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hsn_sac', sa.String(length=8), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_inclusive', sa.Boolean(), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cess', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['expense_item_id'], ['expense_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_lines_voucher_id'), 'voucher_lines', ['voucher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voucher_lines_voucher_id'), table_name='voucher_lines')
    op.drop_table('voucher_lines')
    op.drop_index(op.f('ix_stock_movements_voucher_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_transfer_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_godown_id'), table_name='stock_movements')
    op.drop_index('ix_stock_business_item_date', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_payment_allocations_voucher_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index('ix_vouchers_party', table_name='vouchers')
    op.drop_index('ix_vouchers_business_type_date', table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_tax_payments_business_id'), table_name='tax_payments')
    op.drop_table('tax_payments')
    op.drop_index(op.f('ix_stock_transfers_business_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_payments_party_id'), table_name='payments')
    op.drop_index('ix_payments_business_date', table_name='payments')
    op.drop_index(op.f('ix_payments_account_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_loan_txns_loan_id'), table_name='loan_txns')
    op.drop_index(op.f('ix_loan_txns_business_id'), table_name='loan_txns')
    op.drop_table('loan_txns')
    op.drop_index(op.f('ix_expense_items_business_id'), table_name='expense_items')
    op.drop_table('expense_items')
    op.drop_index(op.f('ix_capital_entries_business_id'), table_name='capital_entries')
    op.drop_table('capital_entries')
    op.drop_index(op.f('ix_account_transfers_business_id'), table_name='account_transfers')
    op.drop_table('account_transfers')
    op.drop_index('ix_parties_business_name', table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_memberships_business_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_loans_business_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index('ix_items_business_name', table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_hsn_codes_business_id'), table_name='hsn_codes')
    op.drop_table('hsn_codes')
    op.drop_index(op.f('ix_godowns_business_id'), table_name='godowns')
    op.drop_table('godowns')
    op.drop_index(op.f('ix_expense_categories_business_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_table('counters')
    op.drop_index(op.f('ix_backups_business_id'), table_name='backups')
    op.drop_table('backups')
    op.drop_index('ix_audit_business_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_accounts_business_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_subscriptions_reseller_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_subscription_payments_account_id'), table_name='subscription_payments')
    op.drop_table('subscription_payments')
    op.drop_index(op.f('ix_license_sales_reseller_id'), table_name='license_sales')
    op.drop_table('license_sales')
    op.drop_index(op.f('ix_businesses_owner_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
