"""recurring invoices

Revision ID: cbc4ac6c3269
Revises: 4c0a00fa858b
Create Date: 2026-10-06 17:42:17.938251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc4ac6c3269'
down_revision: Union[str, Sequence[str], None] = '4c0a00fa858b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_invoices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('party_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template', sa.JSON(), nullable=False),
    sa.Column('frequency', sa.String(length=12), nullable=False),
    sa.Column('interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_date', sa.Date(), nullable=True),
    sa.Column('due_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('auto_email', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=10), server_default='ACTIVE', nullable=False),
    sa.Column('generated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_invoices_business_id'), 'recurring_invoices', ['business_id'], unique=False)
    op.create_index(op.f('ix_recurring_invoices_next_date'), 'recurring_invoices', ['next_date'], unique=False)
    op.create_index(op.f('ix_recurring_invoices_party_id'), 'recurring_invoices', ['party_id'], unique=False)
    op.add_column('vouchers', sa.Column('recurring_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_vouchers_recurring_id'), 'vouchers', ['recurring_id'], unique=False)
    op.create_foreign_key(None, 'vouchers', 'recurring_invoices', ['recurring_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'vouchers', type_='foreignkey')
    op.drop_index(op.f('ix_vouchers_recurring_id'), table_name='vouchers')
    op.drop_column('vouchers', 'recurring_id')
    op.drop_index(op.f('ix_recurring_invoices_party_id'), table_name='recurring_invoices')
    op.drop_index(op.f('ix_recurring_invoices_next_date'), table_name='recurring_invoices')
    op.drop_index(op.f('ix_recurring_invoices_business_id'), table_name='recurring_invoices')
    op.drop_table('recurring_invoices')
    # ### end Alembic commands ###
