"""compliance filings

Revision ID: f14c03e44cf7
Revises: 865e6487691d
Create Date: 2026-10-06 21:48:23.694130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14c03e44cf7'
down_revision: Union[str, Sequence[str], None] = '865e6487691d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_filings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('rule_code', sa.String(length=30), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('done_on', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'rule_code', 'period_key', name='uq_compliance_filing')
    )
    op.create_index(op.f('ix_compliance_filings_business_id'), 'compliance_filings', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_filings_business_id'), table_name='compliance_filings')
    op.drop_table('compliance_filings')
    # ### end Alembic commands ###
