"""gstin lookups

Revision ID: f53cbbf2a5ec
Revises: b5195bcb8dd1
Create Date: 2026-09-25 18:40:12.080496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53cbbf2a5ec'
down_revision: Union[str, Sequence[str], None] = 'b5195bcb8dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gstin_lookups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('business_id', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('credits_remaining', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gstin_lookups_business_id'), 'gstin_lookups', ['business_id'], unique=False)
    op.create_index(op.f('ix_gstin_lookups_created_at'), 'gstin_lookups', ['created_at'], unique=False)
    op.create_index(op.f('ix_gstin_lookups_gstin'), 'gstin_lookups', ['gstin'], unique=False)
    op.create_index(op.f('ix_gstin_lookups_user_id'), 'gstin_lookups', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gstin_lookups_user_id'), table_name='gstin_lookups')
    op.drop_index(op.f('ix_gstin_lookups_gstin'), table_name='gstin_lookups')
    op.drop_index(op.f('ix_gstin_lookups_created_at'), table_name='gstin_lookups')
    op.drop_index(op.f('ix_gstin_lookups_business_id'), table_name='gstin_lookups')
    op.drop_table('gstin_lookups')
    # ### end Alembic commands ###
